version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: trucksigns_db
      POSTGRES_USER: trucksigns_user
      POSTGRES_PASSWORD: supertrucksignsuser!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypointh.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./truck_signs_designs/settings/.env
    depends_on:
      - db

volumes:
  postgres_data:
